[theme]
base = "light"
primaryColor = "#CC0000"
backgroundColor = "#F7F7F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#202020"
font = "sans-serif"

[server]
maxUploadSize = 200
headless = true

[browser]
gatherUsageStats = false
